export const colors = {
  primitive: {
    white:       '#FFFFFF',
    black:       '#000000',
    gray100:     '#F2F2F2',
    gray600:     '#444444',
    orange100:   '#FFF3E8',
    orange200:   '#FFDDB5',
    orange400:   '#FF8C42',
    orange500:   '#F97316',
    orange600:   '#D4601A',
    orange700:   '#7A3000',
    purple300:   '#9395ff',
    purple400:   '#8382e2',
    purple500:   '#5b41eb',
    purple600:   '#681ABB',
    coolGray100: '#eeeef3',
    coolGray200: '#e2e3e5',
    coolGray400: '#8a949e',
    coolGray500: '#555555',
    yellowAccent: '#fded7c',
  },
  semantic: {
    brandPrimary:   'var(--color-brand-primary)',
    brandSecondary: 'var(--color-brand-secondary)',
    brandSubtle:    'var(--color-brand-subtle)',
    bgBase:         'var(--color-bg-base)',
    bgBaseSubtle:   'var(--color-bg-base-subtle)',
    bgSubtle:       'var(--color-bg-subtle)',
    textPrimary:    'var(--color-text-primary)',
    textSecondary:  'var(--color-text-secondary)',
    borderDefault:  'var(--color-border-default)',
    accentOrange:   'var(--color-accent-orange)',
    accentPurple:   'var(--color-accent-purple)',
  },
};

export const spacing = {
  6:  '6px',
  8:  '8px',
  10: '10px',
  16: '16px',
  20: '20px',
  24: '24px',
  32: '32px',
  36: '36px',
  48: '48px',
  56: '56px',
  100: '100px',
};

export const typography = {
  fontFamily: {
    display: "'Recipekorea', sans-serif",
    body:    "'Pretendard', sans-serif",
  },
  styles: {
    headingTitle:      { fontFamily: 'display', size: '83px', weight: 400, lineHeight: 1.3,  letterSpacing: '-1.5px' },
    headingBold50:     { fontFamily: 'body',    size: '50px', weight: 700, lineHeight: 1.5,  letterSpacing: 0 },
    headingSubtitle:   { fontFamily: 'display', size: '32px', weight: 400, lineHeight: 1.1,  letterSpacing: '-2px' },
    headingRegular32:  { fontFamily: 'body',    size: '32px', weight: 400, lineHeight: 1.5,  letterSpacing: 0 },
    titleBold28:       { fontFamily: 'body',    size: '28px', weight: 700, lineHeight: 1.5,  letterSpacing: 0 },
    titleBold24:       { fontFamily: 'body',    size: '24px', weight: 700, lineHeight: 1.5,  letterSpacing: 0 },
    bodyMedium20:      { fontFamily: 'body',    size: '20px', weight: 500, lineHeight: 1.5,  letterSpacing: 0 },
    bodyMedium17:      { fontFamily: 'body',    size: '17px', weight: 500, lineHeight: 1.5,  letterSpacing: 0 },
    hero:              { fontFamily: 'body',    size: '62px', weight: 700, lineHeight: 1.2,  letterSpacing: '-1.24px' },
    sectionSemibold:   { fontFamily: 'body',    size: '36px', weight: 600, lineHeight: 1.5,  letterSpacing: '-0.72px' },
  },
};
